test:
  adapter: mysql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: root
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: canvas_queue_test
    host: localhost
    username: canvas
    timeout: 5000

development:
  adapter: mysql
  encoding: utf8
  database: canvas_development
  host: localhost
  username: root
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: canvas_queue_development
    host: localhost
    username: root
    timeout: 5000
    
production:
  adapter: mysql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: root
  password: 
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: canvas_queue_production
    host: localhost
    username: root
    password: 
    timeout: 5000
